version: '3'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=catolica001
      - MYSQL_PASSWORD=catolica001
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=matias

  app:
    image: nextcloud
    restart: always
    command: sh -c "sudo docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiYmNjN2ViZmFjYTVkODg4Mzc5NjgxNWM5YTI1NWM1MDIiLCJ0IjoiODg3ZWY4MWMtZGQ0MS00OGJhLTk3NjgtYjAwMDA2NDU0NDBjIiwicyI6Ik5EZzRPVGc0TkRJdFpEWTVZeTAwTkdNNExXRmxNalF0WVRRelpUZG1OemRoTTJGbSJ9"
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=catolica001
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=matias
      - MYSQL_HOST=db

volumes:
  db:
  nextcloud:
