version: '3'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=catolica001
      - MYSQL_PASSWORD=catolica001
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=matias

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=catolica001
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=matias
      - MYSQL_HOST=db

volumes:
  db:
  nextcloud:
